/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as readerRouteRouteImport } from './routes/(reader)/route'
import { Route as publicRouteRouteImport } from './routes/(public)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as adminRouteRouteImport } from './routes/(admin)/route'
import { Route as publicIndexRouteImport } from './routes/(public)/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as publicAboutRouteImport } from './routes/(public)/about'
import { Route as appLibraryRouteImport } from './routes/(app)/library'
import { Route as readerReadIndexRouteImport } from './routes/(reader)/read/index'
import { Route as adminAdminIndexRouteImport } from './routes/(admin)/admin/index'
import { Route as readerReadBookIdRouteImport } from './routes/(reader)/read/$bookId'
import { Route as publicBooksBookSlugRouteImport } from './routes/(public)/books/$bookSlug'
import { Route as adminAdminUsersRouteImport } from './routes/(admin)/admin/users'
import { Route as adminAdminIngestionRouteImport } from './routes/(admin)/admin/ingestion'
import { Route as adminAdminBooksRouteImport } from './routes/(admin)/admin/books'
import { Route as adminAdminAuditRouteImport } from './routes/(admin)/admin/audit'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const readerRouteRoute = readerRouteRouteImport.update({
  id: '/(reader)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicRouteRoute = publicRouteRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const adminRouteRoute = adminRouteRouteImport.update({
  id: '/(admin)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicIndexRoute = publicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => publicRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const publicAboutRoute = publicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => publicRouteRoute,
} as any)
const appLibraryRoute = appLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => appRouteRoute,
} as any)
const readerReadIndexRoute = readerReadIndexRouteImport.update({
  id: '/read/',
  path: '/read/',
  getParentRoute: () => readerRouteRoute,
} as any)
const adminAdminIndexRoute = adminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => adminRouteRoute,
} as any)
const readerReadBookIdRoute = readerReadBookIdRouteImport.update({
  id: '/read/$bookId',
  path: '/read/$bookId',
  getParentRoute: () => readerRouteRoute,
} as any)
const publicBooksBookSlugRoute = publicBooksBookSlugRouteImport.update({
  id: '/books/$bookSlug',
  path: '/books/$bookSlug',
  getParentRoute: () => publicRouteRoute,
} as any)
const adminAdminUsersRoute = adminAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminAdminIngestionRoute = adminAdminIngestionRouteImport.update({
  id: '/admin/ingestion',
  path: '/admin/ingestion',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminAdminBooksRoute = adminAdminBooksRouteImport.update({
  id: '/admin/books',
  path: '/admin/books',
  getParentRoute: () => adminRouteRoute,
} as any)
const adminAdminAuditRoute = adminAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => adminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/library': typeof appLibraryRoute
  '/about': typeof publicAboutRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof publicIndexRoute
  '/admin/audit': typeof adminAdminAuditRoute
  '/admin/books': typeof adminAdminBooksRoute
  '/admin/ingestion': typeof adminAdminIngestionRoute
  '/admin/users': typeof adminAdminUsersRoute
  '/books/$bookSlug': typeof publicBooksBookSlugRoute
  '/read/$bookId': typeof readerReadBookIdRoute
  '/admin/': typeof adminAdminIndexRoute
  '/read/': typeof readerReadIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/library': typeof appLibraryRoute
  '/about': typeof publicAboutRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/': typeof publicIndexRoute
  '/admin/audit': typeof adminAdminAuditRoute
  '/admin/books': typeof adminAdminBooksRoute
  '/admin/ingestion': typeof adminAdminIngestionRoute
  '/admin/users': typeof adminAdminUsersRoute
  '/books/$bookSlug': typeof publicBooksBookSlugRoute
  '/read/$bookId': typeof readerReadBookIdRoute
  '/admin': typeof adminAdminIndexRoute
  '/read': typeof readerReadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(admin)': typeof adminRouteRouteWithChildren
  '/(app)': typeof appRouteRouteWithChildren
  '/(public)': typeof publicRouteRouteWithChildren
  '/(reader)': typeof readerRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/(app)/library': typeof appLibraryRoute
  '/(public)/about': typeof publicAboutRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/signup': typeof AuthSignupRoute
  '/(public)/': typeof publicIndexRoute
  '/(admin)/admin/audit': typeof adminAdminAuditRoute
  '/(admin)/admin/books': typeof adminAdminBooksRoute
  '/(admin)/admin/ingestion': typeof adminAdminIngestionRoute
  '/(admin)/admin/users': typeof adminAdminUsersRoute
  '/(public)/books/$bookSlug': typeof publicBooksBookSlugRoute
  '/(reader)/read/$bookId': typeof readerReadBookIdRoute
  '/(admin)/admin/': typeof adminAdminIndexRoute
  '/(reader)/read/': typeof readerReadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/library'
    | '/about'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/'
    | '/admin/audit'
    | '/admin/books'
    | '/admin/ingestion'
    | '/admin/users'
    | '/books/$bookSlug'
    | '/read/$bookId'
    | '/admin/'
    | '/read/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/library'
    | '/about'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/'
    | '/admin/audit'
    | '/admin/books'
    | '/admin/ingestion'
    | '/admin/users'
    | '/books/$bookSlug'
    | '/read/$bookId'
    | '/admin'
    | '/read'
  id:
    | '__root__'
    | '/(admin)'
    | '/(app)'
    | '/(public)'
    | '/(reader)'
    | '/auth'
    | '/(app)/library'
    | '/(public)/about'
    | '/auth/forgot-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/(public)/'
    | '/(admin)/admin/audit'
    | '/(admin)/admin/books'
    | '/(admin)/admin/ingestion'
    | '/(admin)/admin/users'
    | '/(public)/books/$bookSlug'
    | '/(reader)/read/$bookId'
    | '/(admin)/admin/'
    | '/(reader)/read/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  adminRouteRoute: typeof adminRouteRouteWithChildren
  appRouteRoute: typeof appRouteRouteWithChildren
  publicRouteRoute: typeof publicRouteRouteWithChildren
  readerRouteRoute: typeof readerRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(reader)': {
      id: '/(reader)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof readerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(admin)': {
      id: '/(admin)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof adminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/': {
      id: '/(public)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof publicIndexRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(public)/about': {
      id: '/(public)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof publicAboutRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(app)/library': {
      id: '/(app)/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof appLibraryRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(reader)/read/': {
      id: '/(reader)/read/'
      path: '/read'
      fullPath: '/read/'
      preLoaderRoute: typeof readerReadIndexRouteImport
      parentRoute: typeof readerRouteRoute
    }
    '/(admin)/admin/': {
      id: '/(admin)/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof adminAdminIndexRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(reader)/read/$bookId': {
      id: '/(reader)/read/$bookId'
      path: '/read/$bookId'
      fullPath: '/read/$bookId'
      preLoaderRoute: typeof readerReadBookIdRouteImport
      parentRoute: typeof readerRouteRoute
    }
    '/(public)/books/$bookSlug': {
      id: '/(public)/books/$bookSlug'
      path: '/books/$bookSlug'
      fullPath: '/books/$bookSlug'
      preLoaderRoute: typeof publicBooksBookSlugRouteImport
      parentRoute: typeof publicRouteRoute
    }
    '/(admin)/admin/users': {
      id: '/(admin)/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof adminAdminUsersRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/admin/ingestion': {
      id: '/(admin)/admin/ingestion'
      path: '/admin/ingestion'
      fullPath: '/admin/ingestion'
      preLoaderRoute: typeof adminAdminIngestionRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/admin/books': {
      id: '/(admin)/admin/books'
      path: '/admin/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof adminAdminBooksRouteImport
      parentRoute: typeof adminRouteRoute
    }
    '/(admin)/admin/audit': {
      id: '/(admin)/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof adminAdminAuditRouteImport
      parentRoute: typeof adminRouteRoute
    }
  }
}

interface adminRouteRouteChildren {
  adminAdminAuditRoute: typeof adminAdminAuditRoute
  adminAdminBooksRoute: typeof adminAdminBooksRoute
  adminAdminIngestionRoute: typeof adminAdminIngestionRoute
  adminAdminUsersRoute: typeof adminAdminUsersRoute
  adminAdminIndexRoute: typeof adminAdminIndexRoute
}

const adminRouteRouteChildren: adminRouteRouteChildren = {
  adminAdminAuditRoute: adminAdminAuditRoute,
  adminAdminBooksRoute: adminAdminBooksRoute,
  adminAdminIngestionRoute: adminAdminIngestionRoute,
  adminAdminUsersRoute: adminAdminUsersRoute,
  adminAdminIndexRoute: adminAdminIndexRoute,
}

const adminRouteRouteWithChildren = adminRouteRoute._addFileChildren(
  adminRouteRouteChildren,
)

interface appRouteRouteChildren {
  appLibraryRoute: typeof appLibraryRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appLibraryRoute: appLibraryRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface publicRouteRouteChildren {
  publicAboutRoute: typeof publicAboutRoute
  publicIndexRoute: typeof publicIndexRoute
  publicBooksBookSlugRoute: typeof publicBooksBookSlugRoute
}

const publicRouteRouteChildren: publicRouteRouteChildren = {
  publicAboutRoute: publicAboutRoute,
  publicIndexRoute: publicIndexRoute,
  publicBooksBookSlugRoute: publicBooksBookSlugRoute,
}

const publicRouteRouteWithChildren = publicRouteRoute._addFileChildren(
  publicRouteRouteChildren,
)

interface readerRouteRouteChildren {
  readerReadBookIdRoute: typeof readerReadBookIdRoute
  readerReadIndexRoute: typeof readerReadIndexRoute
}

const readerRouteRouteChildren: readerRouteRouteChildren = {
  readerReadBookIdRoute: readerReadBookIdRoute,
  readerReadIndexRoute: readerReadIndexRoute,
}

const readerRouteRouteWithChildren = readerRouteRoute._addFileChildren(
  readerRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  adminRouteRoute: adminRouteRouteWithChildren,
  appRouteRoute: appRouteRouteWithChildren,
  publicRouteRoute: publicRouteRouteWithChildren,
  readerRouteRoute: readerRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
