/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReaderIndexRouteImport } from './routes/reader/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ReaderBookIdRouteImport } from './routes/reader/$bookId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminIngestionRouteImport } from './routes/admin/ingestion'
import { Route as AdminBooksRouteImport } from './routes/admin/books'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderIndexRoute = ReaderIndexRouteImport.update({
  id: '/reader/',
  path: '/reader/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReaderBookIdRoute = ReaderBookIdRouteImport.update({
  id: '/reader/$bookId',
  path: '/reader/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIngestionRoute = AdminIngestionRouteImport.update({
  id: '/admin/ingestion',
  path: '/admin/ingestion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBooksRoute = AdminBooksRouteImport.update({
  id: '/admin/books',
  path: '/admin/books',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/ingestion': typeof AdminIngestionRoute
  '/admin/users': typeof AdminUsersRoute
  '/reader/$bookId': typeof ReaderBookIdRoute
  '/admin/': typeof AdminIndexRoute
  '/reader/': typeof ReaderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/ingestion': typeof AdminIngestionRoute
  '/admin/users': typeof AdminUsersRoute
  '/reader/$bookId': typeof ReaderBookIdRoute
  '/admin': typeof AdminIndexRoute
  '/reader': typeof ReaderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/books': typeof AdminBooksRoute
  '/admin/ingestion': typeof AdminIngestionRoute
  '/admin/users': typeof AdminUsersRoute
  '/reader/$bookId': typeof ReaderBookIdRoute
  '/admin/': typeof AdminIndexRoute
  '/reader/': typeof ReaderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin/audit'
    | '/admin/books'
    | '/admin/ingestion'
    | '/admin/users'
    | '/reader/$bookId'
    | '/admin/'
    | '/reader/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/audit'
    | '/admin/books'
    | '/admin/ingestion'
    | '/admin/users'
    | '/reader/$bookId'
    | '/admin'
    | '/reader'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/admin/audit'
    | '/admin/books'
    | '/admin/ingestion'
    | '/admin/users'
    | '/reader/$bookId'
    | '/admin/'
    | '/reader/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminBooksRoute: typeof AdminBooksRoute
  AdminIngestionRoute: typeof AdminIngestionRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ReaderBookIdRoute: typeof ReaderBookIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ReaderIndexRoute: typeof ReaderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader/': {
      id: '/reader/'
      path: '/reader'
      fullPath: '/reader/'
      preLoaderRoute: typeof ReaderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reader/$bookId': {
      id: '/reader/$bookId'
      path: '/reader/$bookId'
      fullPath: '/reader/$bookId'
      preLoaderRoute: typeof ReaderBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ingestion': {
      id: '/admin/ingestion'
      path: '/admin/ingestion'
      fullPath: '/admin/ingestion'
      preLoaderRoute: typeof AdminIngestionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/books': {
      id: '/admin/books'
      path: '/admin/books'
      fullPath: '/admin/books'
      preLoaderRoute: typeof AdminBooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminBooksRoute: AdminBooksRoute,
  AdminIngestionRoute: AdminIngestionRoute,
  AdminUsersRoute: AdminUsersRoute,
  ReaderBookIdRoute: ReaderBookIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ReaderIndexRoute: ReaderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
