create extension if not exists pgcrypto;

create table if not exists public.books (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  author text not null default 'Unknown',
  description text,
  status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  epub_url text not null,
  cover_url text,
  chapter_count integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.book_chapters (
  id bigint generated by default as identity primary key,
  book_id uuid not null references public.books(id) on delete cascade,
  chapter_index integer not null,
  title text not null,
  html text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (book_id, chapter_index)
);

create table if not exists public.user_roles (
  user_id text not null,
  role text not null check (role in ('user', 'admin')),
  created_at timestamptz not null default now(),
  primary key (user_id, role)
);

create table if not exists public.user_preferences (
  user_id text primary key,
  theme text not null default 'dark',
  font_size integer not null default 18,
  line_height numeric not null default 1.75,
  prefetch_back integer not null default 10,
  prefetch_ahead integer not null default 30,
  updated_at timestamptz not null default now()
);

create table if not exists public.reading_progress (
  user_id text not null,
  book_id uuid not null references public.books(id) on delete cascade,
  current_chapter integer not null default 0,
  scroll_percent numeric not null default 0,
  client_updated_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key (user_id, book_id)
);

create table if not exists public.bookmarks (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,
  book_id uuid not null references public.books(id) on delete cascade,
  chapter_index integer not null,
  scroll_percent numeric not null default 0,
  excerpt text not null default '',
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists public.reading_events (
  id uuid primary key default gen_random_uuid(),
  user_id text,
  book_id uuid references public.books(id) on delete set null,
  session_id text,
  event_name text not null,
  event_ts timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb,
  ingested_at timestamptz not null default now()
);

create table if not exists public.ingestion_jobs (
  id uuid primary key default gen_random_uuid(),
  book_id uuid references public.books(id) on delete set null,
  submitted_by text,
  status text not null check (status in ('queued', 'processing', 'failed', 'done')),
  error text,
  stats jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz
);

create table if not exists public.admin_audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_user_id text not null,
  action text not null,
  entity_type text not null,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists books_status_idx on public.books(status);
create index if not exists books_updated_at_idx on public.books(updated_at desc);
create index if not exists book_chapters_book_idx on public.book_chapters(book_id, chapter_index);
create index if not exists reading_progress_book_idx on public.reading_progress(book_id);
create index if not exists bookmarks_lookup_idx on public.bookmarks(user_id, book_id, created_at desc);
create index if not exists reading_events_user_ts_idx on public.reading_events(user_id, event_ts desc);
create index if not exists reading_events_book_ts_idx on public.reading_events(book_id, event_ts desc);
create index if not exists audit_logs_created_at_idx on public.admin_audit_logs(created_at desc);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists books_touch_updated_at on public.books;
create trigger books_touch_updated_at
before update on public.books
for each row
execute function public.touch_updated_at();

drop trigger if exists book_chapters_touch_updated_at on public.book_chapters;
create trigger book_chapters_touch_updated_at
before update on public.book_chapters
for each row
execute function public.touch_updated_at();

drop trigger if exists user_preferences_touch_updated_at on public.user_preferences;
create trigger user_preferences_touch_updated_at
before update on public.user_preferences
for each row
execute function public.touch_updated_at();

drop trigger if exists reading_progress_touch_updated_at on public.reading_progress;
create trigger reading_progress_touch_updated_at
before update on public.reading_progress
for each row
execute function public.touch_updated_at();

drop trigger if exists bookmarks_touch_updated_at on public.bookmarks;
create trigger bookmarks_touch_updated_at
before update on public.bookmarks
for each row
execute function public.touch_updated_at();
